### PR TITLE
Truncate user names when necessary (fixes #28) and fix alignment of sent/received fields

### LINKED ISSUE #28: Text is garbled if the user name is long
I compiled nethogs from source. It works but the output is messed up if the user name is long. Here i have a user name in the form of abcdef.abcdefg@abcdefg.abcd (Active Directory user).
Here is the line with a process called iceweasel:

`2957 abcdef.abiceweaseldefg.abcd  br0        2.913      13.272 KB/sec`

Notice that the first 9 letters are followed by the program name then followed by some other letters from the user name.

### PR DESCRIPTION
**Pull request by nibroc**
* Fixes #28 -- the username would overflow and mix in with the program name
* Unit column no longer leaves an unnecessary empty space at the end of the line. 
* Received column lines up correctly to the RECEIVED label (are the SENT header and the column values purposely offset???)

Hopefully I'm not stepping on anyone's toes since this issue wasn't tagged as help-wanted, but it seemed easy and a nice improvement. I'm a bit confused on what style to use since the README.md says braces on same lines for conditionals but the code has a mix of everything, so I went with same line. Also, hopefully my refactoring hasn't gone too far... It was a bit overwhelming to see so many numbers shuffling around :).

Before:
before

Note the "KB/sec" has a trailing space, "0.114" isn't lined up with RECEIVED, and the username has overflowed its column and has "curl" in the middle of it.

After:
after

The trailing space is fixed, "0.114" lines up with RECEIVED, and the username is truncated. I thought the prefixed continuation looked a bit odd with usernames so I went with suffixed, but I can change that if preferred.

### CODE REVIEW

**Comment by raboof** [comment]
Hi Corbin,

Thanks so much for your contribution! Certainly not stepping on any toes, much appreciated.

Yeah, the style currently isn't very consistent - most of that code was written more than 10 years ago, I blame my younger self :).

Thanks for the refactoring, looks good!

File: cui.cpp [hunk 1]
```diff
@@ -109,47 +119,85 @@ std::string uid2username (uid_t uid)
...
-		free (tmp);
-	} else {
-		mvprintw (row, 8 + 9, "%s", m_name);
-	}
-	mvprintw (row, 8 + 9 + proglen + 2, "%s", devicename);
-	mvprintw (row, 8 + 9 + proglen + 2 + 6, "%10.3f", sent_value);
-	mvprintw (row, 8 + 9 + proglen + 2 + 6 + 9 + 3, "%10.3f", recv_value);
+	mvaddstr_truncate_trailing (row, column_offset_user, username.c_str(), username.size(), COLUMN_WIDTH_USER);
+
+	// PROGRAM column
```
Comment (raboof) [inline cui.cpp]: I think we can do without these comments - the parameter names speak for themselves

File: cui.cpp [hunk 2]
```diff
@@ -109,47 +119,85 @@ std::string uid2username (uid_t uid)
...
-		start[1] = '.';
-		mvprintw (row, 8 + 9, "%s", start);
-		free (tmp);
-	} else {
-		mvprintw (row, 8 + 9, "%s", m_name);
-	}
-	mvprintw (row, 8 + 9 + proglen + 2, "%s", devicename);
-	mvprintw (row, 8 + 9 + proglen + 2 + 6, "%10.3f", sent_value);
-	mvprintw (row, 8 + 9 + proglen + 2 + 6 + 9 + 3, "%10.3f", recv_value);
+	mvaddstr_truncate_trailing (row, column_offset_user, username.c_str(), username.size(), COLUMN_WIDTH_USER);
```
Comment (raboof) [inline cui.cpp]: `mvaddstr_truncate_trailing` indeed makes more sense here

**Comment by raboof** [comment]
Right now the numbers in the 'totals' line don't align exactly with those in the individual lines - is that intentional? Doesn't look too bad.

**Comment by nibroc** [comment]
I cleaned up the noisy comments and aligned the totals column (it was indeed on accident -- just didn't notice it). Hopefully it's good now!

**Comment by raboof** [comment]
Looks great thanks again!
